# Generated by Django 3.1.1 on 2020-10-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officehours', '0003_add_online_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
