# Generated by Django 2.2.6 on 2019-11-03 19:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('ais_num', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=4)),
                ('catalog_code', models.IntegerField(validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)])),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('state', models.PositiveIntegerField(choices=[(10, 'Open'), (20, 'Closed')], default=20)),
                ('url_slug', models.CharField(max_length=256, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(max_length=64)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.CourseOffering')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service_start_time', models.TimeField(blank=True, null=True)),
                ('service_end_time', models.TimeField(blank=True, null=True)),
                ('state', models.PositiveIntegerField(choices=[(10, 'Pending'), (20, 'Scheduled'), (30, 'In Progress'), (40, 'Completed'), (50, 'No-show'), (60, 'Could not schedule'), (70, 'Cancelled'), (80, 'Invalid')], default=10)),
                ('type', models.PositiveIntegerField(choices=[(10, 'Regular'), (20, 'Express')], default=10)),
                ('description', models.TextField()),
                ('actual_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_slot', to='webapp.Slot')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.CourseOffering')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('slots', models.ManyToManyField(to='webapp.Slot')),
                ('students', models.ManyToManyField(related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('ais_num', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('quarter', models.CharField(choices=[('aut', 'Autumn'), ('win', 'Winter'), ('spr', 'Spring'), ('sum', 'Summer')], max_length=3)),
            ],
            options={
                'unique_together': {('year', 'quarter')},
            },
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='quarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Quarter'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='servers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('course', 'quarter')},
        ),
    ]
